import type { Metadata } from "next";
import { DEFAULT_LOCALE, getDictionary, localePath, type Locale, type PageKey } from "@/lib/i18n";
import { SITE_NAME, SITE_URL } from "@/lib/site";

// OG images per language, generated by scripts/generate-brand-assets.mjs into public/og.
function openGraph(locale: Locale, url: string, title: string): Metadata["openGraph"] {
  return {
    type: "website",
    siteName: SITE_NAME,
    locale: locale === "fr" ? "fr_FR" : "en_GB",
    url,
    title,
    images: [{ url: `/og/${locale}.png`, width: 1200, height: 630, alt: SITE_NAME }],
  };
}

/** Root layout metadata for one language tree: base URL and the "Page · Polo Brokers" template. */
export function rootMetadata(locale: Locale): Metadata {
  return {
    metadataBase: new URL(SITE_URL),
    title: { default: SITE_NAME, template: `%s · ${SITE_NAME}` },
    applicationName: SITE_NAME,
    openGraph: openGraph(locale, localePath(locale, "home"), SITE_NAME),
    twitter: { card: "summary_large_image" },
  };
}

/** Per page: title, canonical, hreflang alternates en / fr / x-default (x-default is EN), OG. */
export function pageMetadata(locale: Locale, page: PageKey): Metadata {
  const dict = getDictionary(locale);
  const canonical = localePath(locale, page);
  const title = page === "home" ? SITE_NAME : `${dict.pages[page]} · ${SITE_NAME}`;
  return {
    title: page === "home" ? { absolute: SITE_NAME } : dict.pages[page],
    alternates: {
      canonical,
      languages: {
        en: localePath("en", page),
        fr: localePath("fr", page),
        "x-default": localePath(DEFAULT_LOCALE, page),
      },
    },
    openGraph: openGraph(locale, canonical, title),
  };
}
